name: Compile project and run C++ tests [Linux]
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test-linux.yml'
      - 'benchmarks/**'
      - 'examples/**'
      - 'sf_compressor/**'
      - 'sources/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/test-linux.yml'
      - 'benchmarks/**'
      - 'examples/**'
      - 'sf_compressor/**'
      - 'sources/**'
      - 'tests/**'
      - 'CMakeLists.txt'

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Build tests, benchmarks and examples
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DSFC_BUILD_TESTS=ON -DSFC_BUILD_BENCHMARKS=ON -DSFC_BUILD_EXAMPLES=ON ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Install sf_compressor
        run: |
          cd build
          sudo cmake --install .

      - name: Check cmake target installation
        run: cmake --find-package -DNAME=sf_compressor -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST